project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - publications.qmd
    - software.qmd
    - conferences.qmd

website:
  title: "HelLucCro"
  navbar:
    search: false
    left:
      - publications.qmd
      - software.qmd
      - conferences.qmd
    right:
      - text: "{{< fa brands google >}}"
        href: https://scholar.google.com/citations?user=HvzwrjEAAAAJ
      - text: "{{< fa brands github >}}"
        href: https://github.com/HelenaLC
      - text: "{{< fa brands twitter >}}"
        href: https://twitter.com/CrowellHL

format:
  html:
    theme: simplex
    fontsize: 1em