project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "HLC"
  navbar:
    search: false
    right:
      - text: "{{< fa brands google >}}"
        href: https://scholar.google.com/citations?user=HvzwrjEAAAAJ
      - text: "{{< fa brands github >}}"
        href: https://github.com/HelenaLC
      - text: "{{< fa brands twitter >}}"
        href: https://bsky.app/profile/helucro.bsky.social

format:
  html:
    theme: flatly
    fontsize: 1em
    keep-tex: true
    toc: true
    toc-float: true
