project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - publications.qmd
    - conferences.qmd
    - software.qmd

website:
  title: "Vitae"
  navbar:
    search: false
    left:
      - publications.qmd
      - conferences.qmd
      - software.qmd
    right:
      - text: "{{< fa brands google >}}"
        href: https://scholar.google.com/citations?user=HvzwrjEAAAAJ
      - text: "{{< fa brands github >}}"
        href: https://github.com/HelenaLC
      - text: "{{< fa brands twitter >}}"
        href: https://bsky.app/profile/helucro.bsky.social

format:
  html:
    theme: flatly
    fontsize: 1em
    keep-tex: true